name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  macos:
    runs-on: macos-13-xlarge

    strategy:
      matrix:
        xcode:
          - "14.3.1" # Swift 5.8.1

    name: "macOS (Xcode ${{ matrix.xcode }})"

    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-spm-xcode-${{ matrix.xcode }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-xcode-${{ matrix.xcode }}-
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
